mnmn: SmartThingsCommunity
vid: 7e1d7af3-a403-3ecd-aaa1-3cc595be8f05
version: 0.0.1
type: profile
dashboard:
    states:
        -
            component: main
            capability: earthbench45333.object
            version: 1
            idx: 0
            group: main
            values: []
            composite: false
    actions: []
    basicPlus: []
detailView:
    -
        component: main
        capability: earthbench45333.object
        version: 1
        values: []
        patch: []
    -
        component: main
        capability: earthbench45333.eye
        version: 1
        values: []
        patch: []
    -
        component: main
        capability: earthbench45333.finger
        version: 1
        values: []
        patch: []
    -
        component: main
        capability: earthbench45333.objnormalizedxy
        version: 1
        values: []
        patch: []
    -
        component: main
        capability: earthbench45333.trigger
        version: 1
        values: []
        patch: []
    -
        component: main
        capability: earthbench45333.direction
        version: 1
        values: []
        patch: []
automation:
    conditions:
        -
            component: main
            capability: earthbench45333.object
            version: 1
            values: []
            patch: []
            exclusion: []
        -
            component: main
            capability: earthbench45333.eye
            version: 1
            values: []
            patch: []
            exclusion: []
        -
            component: main
            capability: earthbench45333.finger
            version: 1
            values: []
            patch: []
            exclusion: []
        -
            component: main
            capability: earthbench45333.objnormalizedxy
            version: 1
            values: []
            patch: []
            exclusion: []
        -
            component: main
            capability: earthbench45333.trigger
            version: 1
            values: []
            patch: []
            exclusion: []
        -
            component: main
            capability: earthbench45333.direction
            version: 1
            values: []
            patch: []
            exclusion: []
    actions: []
presentationId: 7e1d7af3-a403-3ecd-aaa1-3cc595be8f05
manufacturerName: SmartThingsCommunity
