dashboard:
  states:
    - label: '{{direction.value}}'
      alternatives: null
  actions: []
  basicPlus: []
detailView:
  - label: 'Current direction'
    displayType: state
    state: 
      value: direction.value
      label: '{{direction.value}}'
      alternatives: null
automation:
  conditions:
    - label: 'Current direction'
      displayType: textField
      textField:
        value: direction.value
  actions: []
id: earthbench45333.direction
version: 1